"""Frida script generation + optional attach (frida-tools optional)."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

from .plugin import HookSpec, parse_hooks_json


class FridaError(RuntimeError):
    pass


def frida_available() -> dict[str, Any]:
    bin_path = shutil.which("frida")
    ps = shutil.which("frida-ps")
    version = None
    if bin_path:
        try:
            version = subprocess.run(
                [bin_path, "--version"], capture_output=True, text=True, timeout=10
            ).stdout.strip()
        except Exception as e:
            version = f"error: {e}"
    return {
        "frida": bin_path,
        "frida_ps": ps,
        "version": version,
        "available": bool(bin_path),
        "hint": None
        if bin_path
        else "pip/uv install frida-tools; phone needs frida-server matching version",
    }


def render_frida_script(
    hooks: list[HookSpec] | str | list | dict | None,
    *,
    title: str = "andra-mcp",
) -> str:
    if hooks is None:
        norm: list[HookSpec] = []
    elif isinstance(hooks, list) and hooks and isinstance(hooks[0], HookSpec):
        norm = list(hooks)  # type: ignore[arg-type]
    else:
        norm = parse_hooks_json(hooks)  # type: ignore[arg-type]

    parts = [
        f"// Generated by andra-mcp ({title})",
        "// Usage: frida -U -f <pkg> -l script.js --no-pause",
        "//    or: frida -U <pkg> -l script.js",
        "",
        "Java.perform(function () {",
        f'  console.log("[*] {title} loaded");',
        "",
    ]
    for i, h in enumerate(norm):
        cn = h.class_name
        mn = h.method_name
        kind = h.kind
        rv = h.return_value
        note = h.note or f"{kind} {cn}.{mn}"
        parts += [
            f"  // [{i}] {note}",
            f"  try {{",
            f'    var C{i} = Java.use("{cn}");',
            f"    var overloads{i} = C{i}.{mn}.overloads;",
            f"    overloads{i}.forEach(function (ol) {{",
            f"      ol.implementation = function () {{",
            f"        var args = [];",
            f"        for (var i = 0; i < arguments.length; i++) args.push(arguments[i]);",
        ]
        if kind == "replace" and rv is not None:
            # best-effort JS literal
            parts += [
                f'        console.log("[replace] {cn}.{mn} args=" + JSON.stringify(args));',
                f"        return {rv};",
            ]
        elif kind == "before" and rv is not None:
            parts += [
                f'        console.log("[before-skip] {cn}.{mn} args=" + JSON.stringify(args));',
                f"        return {rv};",
            ]
        elif kind == "after" and rv is not None:
            parts += [
                f"        var ret = ol.apply(this, arguments);",
                f'        console.log("[after] {cn}.{mn} ret=" + ret + " -> override");',
                f"        return {rv};",
            ]
        else:
            parts += [
                f'        console.log("[call] {cn}.{mn} args=" + JSON.stringify(args.map(String)));',
                f"        var ret = ol.apply(this, arguments);",
                f'        console.log("[ret ] {cn}.{mn} => " + ret);',
                f"        return ret;",
            ]
        parts += [
            f"      }};",
            f"    }});",
            f'    console.log("[+] hooked {cn}.{mn} (" + overloads{i}.length + " overloads)");',
            f"  }} catch (e) {{",
            f'    console.log("[-] hook failed {cn}.{mn}: " + e);',
            f"  }}",
            "",
        ]
    parts += ["});", ""]
    return "\n".join(parts)


def write_frida_script(
    out_path: Path,
    hooks: list | str | dict,
    *,
    title: str = "andra-mcp",
) -> dict[str, Any]:
    out_path = out_path.expanduser().resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    body = render_frida_script(hooks, title=title)
    out_path.write_text(body, encoding="utf-8")
    return {
        "ok": True,
        "path": str(out_path),
        "bytes": len(body.encode("utf-8")),
        "frida": frida_available(),
        "run_examples": [
            f"frida -U -f <package> -l {out_path} --no-pause",
            f"frida -U <package> -l {out_path}",
        ],
    }


def frida_attach(
    package: str,
    script_path: Path,
    *,
    serial: str | None = None,
    spawn: bool = True,
    timeout_sec: float = 12,
) -> dict[str, Any]:
    """
    Best-effort frida run for a short window; capture stdout.
    Requires frida-tools on host + frida-server on device.
    """
    info = frida_available()
    if not info["available"]:
        raise FridaError(info["hint"] or "frida not installed")

    script_path = script_path.expanduser().resolve()
    if not script_path.exists():
        raise FridaError(f"Script not found: {script_path}")

    cmd = [info["frida"]]
    # device
    if serial:
        cmd += ["-D", serial]
    else:
        cmd += ["-U"]

    if spawn:
        cmd += ["-f", package, "-l", str(script_path), "--no-pause"]
    else:
        cmd += [package, "-l", str(script_path)]

    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout_sec,
            env={**os.environ},
        )
        return {
            "ok": proc.returncode == 0,
            "command": cmd,
            "returncode": proc.returncode,
            "stdout": (proc.stdout or "")[-8000:],
            "stderr": (proc.stderr or "")[-4000:],
            "note": "Short attach window; for interactive use run frida manually.",
        }
    except subprocess.TimeoutExpired as e:
        out = (e.stdout or "") if isinstance(e.stdout, str) else (e.stdout or b"").decode("utf-8", "replace")
        err = (e.stderr or "") if isinstance(e.stderr, str) else (e.stderr or b"").decode("utf-8", "replace")
        return {
            "ok": True,
            "command": cmd,
            "returncode": None,
            "timeout": True,
            "stdout": out[-8000:],
            "stderr": err[-4000:],
            "note": f"Stopped after {timeout_sec}s (expected for non-interactive capture).",
        }
