"""Generate Andra plugin packages (plugin.json + main.bsh + hooks)."""

from __future__ import annotations

import json
import re
import zipfile
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Literal


HookKind = Literal["before", "after", "replace", "log"]

# Phone-side paths under Andra runtime.
# Preferred: host-owned media dir (readable inside target process under scoped storage):
#   /sdcard/Android/media/<targetPackage>/Andra/plugins/<Name>/
# Fallback public root (may be invisible to apps without all-files access):
#   /sdcard/Andra/plugins/<Name>/
RUNTIME_PKG = "dev.andra.runtime"
PHONE_PLUGINS_ROOT = "/sdcard/Andra/plugins"


@dataclass
class HookSpec:
    """One hook target emitted into main.bsh and hooks.json."""

    class_name: str
    method_name: str
    kind: HookKind = "log"
    return_value: str | None = None
    note: str = ""


@dataclass
class PluginMeta:
    name: str
    author: str = "andra-mcp"
    version: str = "1.0.0"
    desc: str = ""
    target_package: str = ""
    """Host app package the runtime should inject into."""


def _safe_folder_name(name: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_\-\u4e00-\u9fa5]", "_", name).strip("_")
    return cleaned or "Plugin"


def phone_plugin_path(folder: str, target_package: str = "") -> str:
    if target_package:
        return (
            f"/sdcard/Android/media/{target_package}/Andra/plugins/{folder}/"
        )
    return f"{PHONE_PLUGINS_ROOT}/{folder}/"


def _hook_block(h: HookSpec, idx: int) -> str:
    """BSH using Andra global API names (forge*)."""
    note = h.note or f"{h.kind} {h.class_name}.{h.method_name}"
    cn = h.class_name
    mn = h.method_name
    lines = [
        f"// --- hook[{idx}] {note} ---",
        f"try {{",
        f'    clazz_{idx} = forgeFindClass("{cn}");',
    ]
    if h.kind == "before":
        if h.return_value is not None:
            body = f"        param.skipWith({h.return_value});"
        else:
            body = (
                f'        forgeLog("[{idx}] before {mn} args=" + '
                f"java.util.Arrays.toString(param.args));"
            )
        lines += [
            f'    forgeHookBefore(clazz_{idx}, "{mn}", param -> {{',
            body,
            f"    }});",
            f'    forgeLog("hooked before {cn}.{mn}");',
        ]
    elif h.kind == "after":
        if h.return_value is not None:
            body = f"        param.result = {h.return_value};"
        else:
            body = f'        forgeLog("[{idx}] after {mn} result=" + param.result);'
        lines += [
            f'    forgeHookAfter(clazz_{idx}, "{mn}", param -> {{',
            body,
            f"    }});",
            f'    forgeLog("hooked after {cn}.{mn}");',
        ]
    elif h.kind == "replace":
        rv = h.return_value if h.return_value is not None else "null"
        lines += [
            f'    forgeHookBefore(clazz_{idx}, "{mn}", param -> {{',
            f"        param.skipWith({rv});",
            f"    }});",
            f'    forgeLog("hooked replace {cn}.{mn} -> {rv}");',
        ]
    else:  # log
        lines += [
            f'    forgeHookBefore(clazz_{idx}, "{mn}", param -> {{',
            f'        forgeLog("[{idx}] CALL {cn}.{mn} args=" + '
            f"java.util.Arrays.toString(param.args));",
            f"    }});",
            f'    forgeHookAfter(clazz_{idx}, "{mn}", param -> {{',
            f'        forgeLog("[{idx}] RET  {cn}.{mn} result=" + param.result);',
            f"    }});",
            f'    forgeLog("hooked log {cn}.{mn}");',
        ]
    lines += [
        f"}} catch (Throwable e_{idx}) {{",
        f'    forgeLog("hook failed [{idx}] {cn}.{mn}: " + e_{idx});',
        f"}}",
        "",
    ]
    return "\n".join(lines)


def render_main_bsh(
    meta: PluginMeta,
    hooks: list[HookSpec] | None = None,
    extra_bsh: str = "",
    analysis_notes: str = "",
) -> str:
    hooks = hooks or []
    header_notes = analysis_notes.strip()
    if header_notes:
        commented = "\n".join(
            "// " + line if line else "//" for line in header_notes.splitlines()
        )
    else:
        commented = "// (no analysis notes)"

    parts = [
        f"// Generated by andra-mcp for Andra runtime",
        f"// Plugin: {meta.name}",
        f"// Target: {meta.target_package or '(set target_package)'}",
        f"//",
        commented,
        f"",
        f'forgeLog("=== plugin {meta.name} v{meta.version} loading ===");',
        f"",
    ]

    if not hooks and not extra_bsh.strip():
        parts += [
            "// No hooks — placeholder so the plugin still loads.",
            'forgeLog("No hooks yet. Edit main.bsh or regenerate with write_plugin.");',
            "",
        ]

    for i, h in enumerate(hooks):
        parts.append(_hook_block(h, i))

    if extra_bsh.strip():
        parts += [
            "// ----- extra script -----",
            extra_bsh.rstrip(),
            "",
        ]

    parts.append(f'forgeLog("=== plugin {meta.name} loaded ===");')
    parts.append("")
    return "\n".join(parts)


def render_install_md(meta: PluginMeta, folder_name: str) -> str:
    pkg = meta.target_package or "<targetPackage>"
    remote = phone_plugin_path(folder_name, pkg if pkg != "<targetPackage>" else "")
    public = phone_plugin_path(folder_name)
    return f"""# {meta.name} — Andra plugin

## Files

- `plugin.json` — metadata + target package
- `hooks.json` — structured hook table (**runtime applies this**; main.bsh is docs-only for now)
- `main.bsh` — documentation / future BSH entry
- `.enabled` — present after deploy to enable

## Phone path (host-readable)

```
{remote}
```

Fallback mirror:

```
{public}
```

Runtime package: `{RUNTIME_PKG}`  
Host to inject: `{pkg}`

## LSPosed scope

- Enable module **Andra** (`{RUNTIME_PKG}`)
- Check **only** host app `{pkg}`
- **Do not require 系统框架 (system)** for app hooks
- After scope change: force-stop host (or reboot) so injection reloads

## Deploy (andra MCP)

1. `adb_connect` to `192.168.x.x:<PORT>` (not 172.19.*)
2. `deploy_plugin` name=`{folder_name}` target_package=`{pkg}`
3. LSPosed: Andra 启用，作用域只勾 `{pkg}`（不要勾系统框架）
4. `verify_plugin` name=`{folder_name}` host_package=`{pkg}`
5. 或随时 `read_andra_log` host_package=`{pkg}` plugin=`{folder_name}` level=IE

```bash
uv run python -m andra.cli deploy {folder_name} --package {pkg}
uv run python -m andra.cli verify {folder_name} --package {pkg}
uv run python -m andra.cli read-log --host {pkg} --plugin {folder_name}
```

## Manual adb

```bash
SERIAL=192.168.x.x:<PORT>
NAME={folder_name}
HOST={pkg}
REMOTE=/sdcard/Android/media/$HOST/Andra/plugins/$NAME
adb -s $SERIAL shell mkdir -p "$REMOTE"
adb -s $SERIAL push plugin.json "$REMOTE/"
adb -s $SERIAL push hooks.json "$REMOTE/"
adb -s $SERIAL push main.bsh "$REMOTE/"
adb -s $SERIAL shell touch "$REMOTE/.enabled"
adb -s $SERIAL shell am force-stop $HOST
```
"""


def write_plugin_package(
    out_root: Path,
    meta: PluginMeta,
    hooks: list[HookSpec] | None = None,
    extra_bsh: str = "",
    analysis_notes: str = "",
    main_bsh: str | None = None,
    overwrite: bool = True,
) -> dict[str, Any]:
    """Write an Andra plugin directory under workspace/plugins/."""
    out_root = out_root.expanduser().resolve()
    folder = _safe_folder_name(meta.name)
    plugin_dir = out_root / folder
    if plugin_dir.exists() and not overwrite:
        n = 1
        while (out_root / f"{folder}_{n}").exists():
            n += 1
        plugin_dir = out_root / f"{folder}_{n}"
        folder = plugin_dir.name
    plugin_dir.mkdir(parents=True, exist_ok=True)

    hooks = hooks or []
    body = (
        main_bsh
        if main_bsh is not None
        else render_main_bsh(
            meta, hooks=hooks, extra_bsh=extra_bsh, analysis_notes=analysis_notes
        )
    )
    install = render_install_md(meta, folder)

    plugin_json = {
        "id": folder,
        "name": meta.name,
        "author": meta.author,
        "version": meta.version,
        "desc": meta.desc or meta.name,
        "targetPackage": meta.target_package,
        "entry": "main.bsh",
        "hooksFile": "hooks.json",
    }
    hooks_json = [asdict(h) for h in hooks]

    (plugin_dir / "plugin.json").write_text(
        json.dumps(plugin_json, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (plugin_dir / "hooks.json").write_text(
        json.dumps(hooks_json, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (plugin_dir / "main.bsh").write_text(body, encoding="utf-8")
    (plugin_dir / "INSTALL.md").write_text(install, encoding="utf-8")

    manifest = {
        "folder": folder,
        "path": str(plugin_dir),
        "meta": asdict(meta),
        "hooks": hooks_json,
        "files": ["plugin.json", "hooks.json", "main.bsh", "INSTALL.md"],
        "deploy_path": phone_plugin_path(folder),
        "runtime_package": RUNTIME_PKG,
    }
    (plugin_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return manifest


def zip_plugin(plugin_dir: Path, zip_path: Path | None = None) -> Path:
    plugin_dir = plugin_dir.expanduser().resolve()
    if zip_path is None:
        zip_path = plugin_dir.with_suffix(".zip")
    zip_path = zip_path.expanduser().resolve()
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in plugin_dir.rglob("*"):
            if p.is_file():
                zf.write(p, arcname=str(p.relative_to(plugin_dir.parent)))
    return zip_path


def parse_hooks_json(raw: str | list | dict | None) -> list[HookSpec]:
    if raw is None or raw == "" or raw == []:
        return []
    if isinstance(raw, str):
        data = json.loads(raw)
    else:
        data = raw
    if isinstance(data, dict):
        data = [data]
    out: list[HookSpec] = []
    for item in data:
        out.append(
            HookSpec(
                class_name=item["class_name"],
                method_name=item["method_name"],
                kind=item.get("kind", "log"),
                return_value=item.get("return_value"),
                note=item.get("note", ""),
            )
        )
    return out


def list_plugins(out_root: Path) -> list[dict[str, Any]]:
    out_root = out_root.expanduser().resolve()
    if not out_root.exists():
        return []
    hits: list[dict[str, Any]] = []
    for d in sorted(out_root.iterdir()):
        if not d.is_dir():
            continue
        pj = d / "plugin.json"
        if not pj.exists() and not (d / "main.bsh").exists():
            continue
        info: dict[str, Any] = {}
        if pj.exists():
            try:
                info = json.loads(pj.read_text(encoding="utf-8"))
            except Exception:
                info = {}
        hits.append(
            {
                "folder": d.name,
                "path": str(d),
                "name": info.get("name", d.name),
                "version": info.get("version", ""),
                "desc": info.get("desc", ""),
                "targetPackage": info.get("targetPackage", ""),
                "main_bsh_bytes": (d / "main.bsh").stat().st_size
                if (d / "main.bsh").exists()
                else 0,
            }
        )
    return hits
